_wandb:
    value:
        cli_version: 0.21.0
        e:
            jiw0zomv06a9a3hxg28ovfw35ztg4sb7:
                codePath: codes\main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1023307624448"
                        used: "931798441984"
                email: nardonej3@wit.edu
                executable: C:\Users\jishy\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: cf95ad06201c92f716b4e1182b8ed5e289cc3fea
                    remote: https://github.com/pangwit/DS_Individual_Project_Example.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-a038da6c-eaf2-e1e0-5cf7-785afc6d756d
                host: DESKTOP-D1HMQRS
                memory:
                    total: "34293710848"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\jishy\Desktop\Coding Projects\DS Project\DS_Individual_Project_Example\codes\main.py
                python: CPython 3.11.0
                root: C:\Users\jishy\Desktop\Coding Projects\DS Project\DS_Individual_Project_Example\codes
                startedAt: "2025-07-27T18:26:48.235007Z"
                writerId: jiw0zomv06a9a3hxg28ovfw35ztg4sb7
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.0
            "5": 0.21.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.21.0
            "13": windows-amd64
critic_layer_sizes:
    value:
        - 1024
        - 1024
        - 512
        - 512
critic_lr:
    value: 0.0001
exp_buffer_size:
    value: 300000
gae_gamma:
    value: 0.99
gae_lambda:
    value: 0.95
min_inference_size:
    value: 29
n_proc:
    value: 32
policy_layer_sizes:
    value:
        - 1024
        - 1024
        - 512
        - 512
policy_lr:
    value: 0.0001
ppo_batch_size:
    value: 100000
ppo_clip_range:
    value: 0.2
ppo_ent_coef:
    value: 0.01
ppo_epochs:
    value: 2
ppo_minibatch_size:
    value: 50000
shm_buffer_size:
    value: 8192
standardize_obs:
    value: false
standardize_returns:
    value: true
timestep_limit:
    value: 1000000000
ts_per_iteration:
    value: 100000
